package org.example.yangi_ishxona.bot;

public enum ChatState {
    NONE,
    REG_FULLNAME,
    REG_POSITION,
    REG_LANGUAGE,

    NEW_PROJECT_NAME,
    NEW_PROJECT_DEADLINE,
    NEW_PROJECT_DESCRIPTION,

    NEW_SPRINT_SELECT_PROJECT,
    NEW_SPRINT_NAME,
    NEW_SPRINT_DEADLINE,

    NEW_TASK_SELECT_PROJECT,
    NEW_TASK_SELECT_SPRINT,
    NEW_TASK_NAME,
    NEW_TASK_SELECT_EXECUTOR,
    NEW_TASK_DEADLINE,
    NEW_TASK_DESCRIPTION,

    AWAIT_COMMENT,
    AWAIT_REVIEW_ATTACHMENT,
    AWAIT_CANCEL_REASON,
    AWAIT_POSTPONE_DEADLINE
}
